spring.application.name=consumidor-guias
server.port=8081

# Base de datos H2 persistente del consumidor
spring.datasource.url=jdbc:h2:file:./data/consumidor-guias-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:duoc}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:duoc123}

# Colas RabbitMQ
app.rabbitmq.guias.exchange=guias.exchange
app.rabbitmq.guias.error-exchange=guias.error.exchange
app.rabbitmq.guias.queue=guias.principal.queue
app.rabbitmq.guias.dlq=guias.dlq.queue
app.rabbitmq.guias.routing-key=guias.creada
app.rabbitmq.guias.error-routing-key=guias.error

# S3
aws.region=${AWS_REGION:us-east-1}
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME:}
aws.s3.enabled=${AWS_S3_ENABLED:false}
aws.access-key-id=${AWS_ACCESS_KEY_ID:}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY:}
aws.session-token=${AWS_SESSION_TOKEN:}